steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'asia-northeast1-docker.pkg.dev/qwiklabs-gcp-02-4c5ab5a1a9c7/garnet-artifact/random-pets:$COMMIT_SHA'
    - '-f'
    - 'lab-01/pets-api/Dockerfile'
    - '.'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'random-pets'
    - '--image'
    - 'asia-northeast1-docker.pkg.dev/qwiklabs-gcp-02-4c5ab5a1a9c7/garnet-artifact/random-pets:$COMMIT_SHA'
    - '--region'
    - 'asia-northeast1'
    - '--port'
    - '5000'
    - '--allow-unauthenticated'
    - '--platform'
    - 'managed'

images:
  - 'asia-northeast1-docker.pkg.dev/qwiklabs-gcp-02-4c5ab5a1a9c7/garnet-artifact/random-pets:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY